# drivers/media/video/samsung/mhl_v1/Makefile
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/
# Aakash Manik
#	aakash.manik@samsung.com
# Licensed under GPLv2


obj-$(CONFIG_VIDEO_MHL_V1) += sii8332.o \
			      sii8332_driver.o 
